spring.application.name=kanbanflow

# MongoDB Config (Default 27017, database kanbanflow)
spring.data.mongodb.uri=mongodb://localhost:27017/kanbanflow

# Server config
server.port=8080

# CORS will be handled globally in config

# Gemini API Integration
google.gemini.api.key=AIzaSyDtyAvptXfAL44J8Zhp_Lk7Ms8sAxvD-KY
google.gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
